# Following are the most fundamentals concepts of Tensorflow

Topics Covered:
1. Introduction to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors and Numpy
5. Using @tf.function


### 1. Introduction to Tensors

In [91]:
# Import tensorflow
import tensorflow as tf


In [92]:
# to check version
print(tf.__version__)

2.19.0


In [93]:
# Create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [94]:
# to check dimenions
scaler.ndim

0

In [95]:
# create a vector (1 dimension)
vector = tf.constant([2, 3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [96]:
vector.ndim

1

In [97]:
# Create matrix (2 dimension)
matrix = tf.constant([[2, 3],
                      [4, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [98]:
# specifying the datatype
matrix1 = tf.constant([[2, 3, 4],
                       [4, 5, 6],
                       [7, 8, 9]], dtype=tf.float32)
matrix1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [99]:
# Create a tensor (n-dimensions)
tensor = tf.constant([[[1, 2],
                       [4, 5]],
                      [[4, 5],
                      [7, 8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 5]],

       [[4, 5],
        [7, 8]]], dtype=int32)>

### 2. Creating tensors with tf.Variable()

In [100]:
# create tensors with tf.Variable(): means you can update the values of tensors
changeable_tensor = tf.Variable([1, 2, 3, 4])
changeable_tensor[0].assign(100)
changeable_tensor

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([100,   2,   3,   4], dtype=int32)>

In [127]:
# if you try to change it in the tf.constant() tensor, you will get error.
unchangeable_tensor = tf.constant([1, 2, 3, 4, 5, 6])
unchangeable_tensor[0].assign(100)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### 3. Creating Random Tensors

In [128]:
# Create random tensors
random_tensor = tf.random.Generator.from_seed(42)  # to set the seed reproducibility
random_tensor1 = random_tensor.normal(shape=(3, 3))
random_tensor1


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [129]:
 # Shuffle the tensor (when you want to shuffle your data so the inherent order dosen't affect)
 tensor1 = tf.constant([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
 tf.random.shuffle(tensor1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [130]:
# shuffle tensor with reproducibility
tf.random.set_seed(42)  # global level random seed
tf.random.shuffle(tensor1, seed=42) # operational level random seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

### 4. Other ways to make tensors

In [131]:
# Creating tensors with all 1 as value
tf.ones(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [132]:
# Creating tensor with all zeros as value
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [133]:
# converting numpy arrays into tensors
import numpy as np
array = np.array([1, 2, 3, 4, 5])
tensor_array = tf.constant(array)
tensor_array

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

### 5. Getting Information from tensors

In [134]:
tensor_2 = tf.zeros(shape = (2, 3, 4, 5))
tensor_2

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [135]:
# Get various attributes from tensors
print('Datatype of every element: ', tensor_2.dtype)
print('Number of dimensions: ', tensor_2.ndim)
print('Shape of tensor: ', tensor_2.shape)
print('Total no. of elements in tensor: ', tf.size(tensor_2))


Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of tensor:  (2, 3, 4, 5)
Total no. of elements in tensor:  tf.Tensor(120, shape=(), dtype=int32)


### 6. Indexing Tensors

In [136]:
# Indexing Tensors
index_tensor = tf.constant([1, 2, 3, 4, 5])
# get the first element
index_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [137]:
# get all the elements
index_tensor[:]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [138]:
# get 2 elements of each dimensions
tensor_2[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [139]:
# get the last item
tensor_2[:, :, :, -1]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [140]:
# get the last element of tensor
tensor_2[-1, -1, -1, -1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [141]:
# Add an extra dimension using tf.newaxis
tensor_2.shape

TensorShape([2, 3, 4, 5])

In [142]:
tensor_3 = tensor_2[..., tf.newaxis]
tensor_3.shape

TensorShape([2, 3, 4, 5, 1])

In [143]:
# Another way to add dimensions
tf.expand_dims(tensor_2, axis=0).shape  # add extra dimension to the first index


TensorShape([1, 2, 3, 4, 5])

In [144]:
# expand the last axis
tf.expand_dims(tensor_2, axis=-1).shape

TensorShape([2, 3, 4, 5, 1])

In [145]:
# reshape the tensor
tf.reshape(tensor_2, shape=(1, 2, 3, 4, 5)).shape

TensorShape([1, 2, 3, 4, 5])

### 7. Manipulating Tensors (tensor operations)


In [146]:
# addition
tensor_3 = tf.constant([[1, 2, 3, 4],
                        [4, 5, 6, 7]])
tensor_3 + 10

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[11, 12, 13, 14],
       [14, 15, 16, 17]], dtype=int32)>

In [147]:
# multiplication
tensor_3 * 10

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10, 20, 30, 40],
       [40, 50, 60, 70]], dtype=int32)>

In [148]:
# subtraction
tensor_3 - 5

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[-4, -3, -2, -1],
       [-1,  0,  1,  2]], dtype=int32)>

In [149]:
# you can use functions to do the same thing
tf.add(tensor_3, 10)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[11, 12, 13, 14],
       [14, 15, 16, 17]], dtype=int32)>

In [150]:
tf.multiply(tensor_3, 10)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10, 20, 30, 40],
       [40, 50, 60, 70]], dtype=int32)>

In [151]:
# Matrix mutiplication
# rules to perform this operation:
# 1. the inner dimensions must match
# 2. The resultant matrix has the shape of the outer dimensions


# matrix 1
matrix1 = tf.constant([[1, 2],
                       [3, 4]])
matrix2 = tf.constant([[5, 6],
                       [7, 8]])

# matmul()
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [152]:
# matrix multiplication with python operator '@'
matrix1 @ matrix2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [153]:
# if you try to do matrix multiplication with shape (2, 3) X (2, 3)  . you will get the error as inner dimension is not same
X = tf.constant([[2, 3, 4],
                 [3, 4, 5]])

Y = tf.constant([[5, 6, 7],
                 [7, 8, 9]])

# the shape is (2, 3) X (2, 3)
tf.matmul(X, Y)



InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul] name: 

In [154]:
# to resolve this, you can reshape or transpose the shape of either X or Y tensor
tf.matmul(X, tf.reshape(Y, shape=(3, 2)))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[63, 69],
       [83, 91]], dtype=int32)>

In [155]:
# same you can do with X
tf.matmul(tf.reshape(X, shape=(3, 2)), Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[31, 36, 41],
       [41, 48, 55],
       [55, 64, 73]], dtype=int32)>

In [156]:
# using transpose method
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[56, 74],
       [74, 98]], dtype=int32)>

In [157]:
# you can also perform matrix multiplication using tf.tensordot()
X , Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 4],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 6, 7],
        [7, 8, 9]], dtype=int32)>)

In [158]:
# dot operation
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[56, 74],
       [74, 98]], dtype=int32)>

### 8. Changing the datatype of tensors

In [159]:
A = tf.constant([1.0, 2.0, 3.0])
A.dtype

tf.float32

In [160]:
# using tf.cast():
B = tf.cast(A, dtype=tf.int32)
B.dtype

tf.int32

In [161]:
# changed datatype form float32 to float16
C = tf.cast(A, dtype=tf.float16)
C.dtype

tf.float16

In [162]:
# change from int32 to float32
D = tf.cast(B, dtype=tf.float32)
D.dtype

tf.float32

### 9. Aggregating Functions


In [163]:
# create a random tensor with values between 0 to 100
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([46, 37, 50,  3, 46, 50, 48,  4, 21,  3, 70, 87, 72, 76, 24, 38, 73,
       19, 71, 24, 45,  5, 58, 21, 58, 35, 13, 42, 99, 63,  4, 37, 38, 59,
       92, 19,  1, 75, 89, 44, 40, 94, 40, 98, 27, 86, 75, 67, 76, 19])>

In [164]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [165]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [166]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [167]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2381>

In [168]:
# Find the Variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=790.675537109375>

In [169]:
# Find the Standard Deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.118953704833984>

In [170]:
# find the positional maximum
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [171]:
E[tf.argmax(E)]  # maximum value

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [172]:
# find the positional minimum
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [173]:
E[tf.argmin(E)] # minimum value

<tf.Tensor: shape=(), dtype=int64, numpy=1>

### 11. Squeezing a tensor (removing all the single dimensions)



In [174]:
G = tf.constant(tf.range(1, 21), shape=(1, 1, 1, 1, 20))

In [175]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 20), dtype=int32, numpy=
array([[[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
           16, 17, 18, 19, 20]]]]], dtype=int32)>

In [176]:
# squeezing removes all the single dimensions from the tensors
tf.squeeze(G)

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int32)>

### 12. One Hot Encoding tensors

In [177]:
# Create a list of indecies
some_list = [0, 1, 2, 3]   # could be red, green, blue, purple

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [178]:
tf.one_hot(some_list, depth=4, on_value='I love deep learning', off_value ='I also love dance')


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also love dance',
        b'I also love dance', b'I also love dance'],
       [b'I also love dance', b'I love deep learning',
        b'I also love dance', b'I also love dance'],
       [b'I also love dance', b'I also love dance',
        b'I love deep learning', b'I also love dance'],
       [b'I also love dance', b'I also love dance', b'I also love dance',
        b'I love deep learning']], dtype=object)>

### 13. Squaring, log, square root


In [179]:
H = tf.range(1, 10)

In [180]:
# Find the square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [181]:
# Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [182]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### 15. Tensorflow with Numpy

In [183]:
# Creating tensor directly from numpy
I = tf.constant(np.array([1., 2., 3., 4., 5.]))
I

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [184]:
# Converting our tensor back to numpy array
np.array(I)

array([1., 2., 3., 4., 5.])

In [185]:
# also this way
I.numpy()

array([1., 2., 3., 4., 5.])